[build.environment]
<<<<<<< Updated upstream
HUGO_VERSION = "0.148.1"
=======
GO_VERSION = "1.24.2"
HUGO_VERSION = "0.148.1"
NODE_VERSION = "22"
TZ = "Europe/Madrid"
>>>>>>> Stashed changes

[build]
publish = "public"
command = "hugo --gc --minify"